### ISSUE TITLE
Python 3 support?

### ISSUE THREAD

**Issue by p-hash** [torre76/gd_shortener#2]
Will this project support Python 3?
Thanks in advance

**Comment by torre76** [comment]
When I wrote this snippet of code I meant to use it only in a Python 2 project.
But when I have some spare time, I will add Python 3 support eventually.

**Comment by torre76** [comment]
You can also take a look to @Hasimir work, which is aiming what you want. 

Here a reference to its current branch b26f9ac6aea99e456d8c544eb57d6e71dca67488.

Hopefully he will submit a pull request sometimes.

**Comment by p-hash** [comment]
Thanks!
